### ISSUE TITLE
DicomStack.to_nifti(embed_meta=True) fails for 5D and 4D dicoms

### ISSUE THREAD

**Issue by AlanKuurstra** [moloney/dcmstack#91] opened 2024-09-19 14:19 UTC
When embedding metadata, DicomStack does not account for 5D or 4D data stored in a single dicom.  

https://github.com/moloney/dcmstack/blob/27856f1b964b7ec9cf6cb5bb8e4b6f25596df4b4/src/dcmstack/dcmstack.py#L961-L975

The if statements on len(data.shape) should also include a condition on len(vol_meta) > 1

**Comment by moloney** [comment] 2024-11-20 07:04
Dupe of #71

**Closed by moloney** 2024-11-20 07:04 UTC
